services:
  postgres:
    container_name: dailies-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    container_name: dailies-valkey
    image: valkey/valkey:8-alpine
    command: --save 60 1 --loglevel warning

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    container_name: dailies-minio
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - minio_data:/data
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

volumes:
  minio_data:
  postgres_data:
